<test-run id="2" testcasecount="47" result="Passed" start-time="2021-06-14 18:42:17.071417" end-time="2021-06-14 18:42:48.922413" duration="31" total="47" passed="30" failed="17" inconclusive="0" skipped="0" asserts="0" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" engine-version="3.6.2"><command-line>/usr/local/bin/pytest pythonapi/tests -v --nunit-xml=APItest-results.xml</command-line><filter><test re="0">pythonapi/tests</test></filter><test-suite id="pythonapi/tests/test_store.py::TestStore" name="pythonapi/tests/test_store.py::TestStore" fullname="pythonapi/tests/test_store.py::TestStore" methodname="" classname="" runstate="Runnable" type="Assembly" testcasecount="12" result="Passed" label="" start-time="2021-06-14 18:42:19.188346" end-time="2021-06-14 18:42:37.691085" duration="18.502739" asserts="0" total="12" passed="8" failed="4" warnings="0" inconclusive="0" skipped="0"><properties><property name="python_version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /></properties><test-case id="103" name="pythonapi/tests/test_store.py::TestStore::test_store_inventory" fullname="pythonapi/tests/test_store.py::TestStore::test_store_inventory" methodname="test_store_inventory" classname="TestStore" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:19.188346" end-time="2021-06-14 18:42:20.560284" duration="1.371938" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:12 Test case for store inventory
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/inventory HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:16 Test Store Inventory PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:12 Test case for store inventory
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/inventory HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:16 Test Store Inventory PASSED]]></output></test-case><test-case id="110" name="pythonapi/tests/test_store.py::TestStore::test_store_place_order[Place order [Data: {&quot;id&quot;:6600,&quot;petId&quot;:66001,&quot;quantity&quot;:7,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;approved&quot;,&quot;complete&quot;:true}], expected code=200]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_place_order[Place order [Data: {&quot;id&quot;:6600,&quot;petId&quot;:66001,&quot;quantity&quot;:7,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;approved&quot;,&quot;complete&quot;:true}], expected code=200]" methodname="test_store_place_order[Place order [Data: {&quot;id&quot;:6600,&quot;petId&quot;:66001,&quot;quantity&quot;:7,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;approved&quot;,&quot;complete&quot;:true}], expected code=200]" classname="TestStore" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:24.063582" end-time="2021-06-14 18:42:25.065234" duration="1.001652" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:21 Test case for placing an order, ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/store/order HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:24 Order with ID=6600 was placed
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6600 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:28 Test Store Place Order PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:21 Test case for placing an order, ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/store/order HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:24 Order with ID=6600 was placed
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6600 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:28 Test Store Place Order PASSED]]></output></test-case><test-case id="111" name="pythonapi/tests/test_store.py::TestStore::test_store_place_order[Place order [Data: {&quot;id&quot;:6601,&quot;petId&quot;:66011,&quot;quantity&quot;:5,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;placed&quot;,&quot;complete&quot;:true}], expected code=200]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_place_order[Place order [Data: {&quot;id&quot;:6601,&quot;petId&quot;:66011,&quot;quantity&quot;:5,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;placed&quot;,&quot;complete&quot;:true}], expected code=200]" methodname="test_store_place_order[Place order [Data: {&quot;id&quot;:6601,&quot;petId&quot;:66011,&quot;quantity&quot;:5,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;placed&quot;,&quot;complete&quot;:true}], expected code=200]" classname="TestStore" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:25.066804" end-time="2021-06-14 18:42:26.043462" duration="0.976658" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:21 Test case for placing an order, ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/store/order HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:24 Order with ID=6601 was placed
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6601 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:28 Test Store Place Order PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:21 Test case for placing an order, ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/store/order HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:24 Order with ID=6601 was placed
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6601 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:28 Test Store Place Order PASSED]]></output></test-case><test-case id="112" name="pythonapi/tests/test_store.py::TestStore::test_store_place_order[Place order [Data: {&quot;id&quot;:6602,&quot;petId&quot;:66021,&quot;quantity&quot;:6,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;delivered&quot;,&quot;complete&quot;:true}], expected code=200]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_place_order[Place order [Data: {&quot;id&quot;:6602,&quot;petId&quot;:66021,&quot;quantity&quot;:6,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;delivered&quot;,&quot;complete&quot;:true}], expected code=200]" methodname="test_store_place_order[Place order [Data: {&quot;id&quot;:6602,&quot;petId&quot;:66021,&quot;quantity&quot;:6,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;delivered&quot;,&quot;complete&quot;:true}], expected code=200]" classname="TestStore" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:26.045776" end-time="2021-06-14 18:42:27.043168" duration="0.997392" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:21 Test case for placing an order, ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/store/order HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:24 Order with ID=6602 was placed
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6602 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:28 Test Store Place Order PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:21 Test case for placing an order, ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/store/order HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:24 Order with ID=6602 was placed
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6602 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:28 Test Store Place Order PASSED]]></output></test-case><test-case id="119" name="pythonapi/tests/test_store.py::TestStore::test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:6600,&quot;petId&quot;:66001,&quot;quantity&quot;:7,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;approved&quot;,&quot;complete&quot;:true}], expected code=200]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:6600,&quot;petId&quot;:66001,&quot;quantity&quot;:7,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;approved&quot;,&quot;complete&quot;:true}], expected code=200]" methodname="test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:6600,&quot;petId&quot;:66001,&quot;quantity&quot;:7,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;approved&quot;,&quot;complete&quot;:true}], expected code=200]" classname="TestStore" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:30.498199" end-time="2021-06-14 18:42:31.037098" duration="0.538899" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_store.TestStore object at 0x7fc85787bfd0&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc85787b370&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_order_find = ('{"id":6600,"petId":66001,"quantity":7,"shipDate":"2021-02-03T19:43:55.849+00:00","status":"approved","complete":true}', 200)

    @mark.order(3)
    def test_store_find_order_by_id(self, api, logger, dp_order_find):
        _order = JsonTransmuter.transmute_from(dp_order_find[0], Order)
        logger.info(f"Test case for finding an order, ID={_order.id}")
        response = api.store_find_order_by_id(_order.id)
&gt;       assert response.code == dp_order_find[1]
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_store.py:35: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_store.py:35: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:33 Test case for finding an order, ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6600 HTTP/1.1" 404 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:33 Test case for finding an order, ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6600 HTTP/1.1" 404 None]]></output></test-case><test-case id="120" name="pythonapi/tests/test_store.py::TestStore::test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:6601,&quot;petId&quot;:66011,&quot;quantity&quot;:5,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;placed&quot;,&quot;complete&quot;:true}], expected code=404]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:6601,&quot;petId&quot;:66011,&quot;quantity&quot;:5,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;placed&quot;,&quot;complete&quot;:true}], expected code=404]" methodname="test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:6601,&quot;petId&quot;:66011,&quot;quantity&quot;:5,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;placed&quot;,&quot;complete&quot;:true}], expected code=404]" classname="TestStore" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:31.039303" end-time="2021-06-14 18:42:31.540769" duration="0.501466" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_store.TestStore object at 0x7fc857a8e5e0&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc85787b370&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_order_find = ('{"id":6601,"petId":66011,"quantity":5,"shipDate":"2021-02-03T19:43:55.849+00:00","status":"placed","complete":true}', 404)

    @mark.order(3)
    def test_store_find_order_by_id(self, api, logger, dp_order_find):
        _order = JsonTransmuter.transmute_from(dp_order_find[0], Order)
        logger.info(f"Test case for finding an order, ID={_order.id}")
        response = api.store_find_order_by_id(_order.id)
&gt;       assert response.code == dp_order_find[1]
E       assert 200 == 404
E         +200
E         -404

pythonapi/tests/test_store.py:35: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_store.py:35: assert 200 == 404]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:33 Test case for finding an order, ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6601 HTTP/1.1" 200 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:33 Test case for finding an order, ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6601 HTTP/1.1" 200 None]]></output></test-case><test-case id="121" name="pythonapi/tests/test_store.py::TestStore::test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:6602,&quot;petId&quot;:66021,&quot;quantity&quot;:6,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;delivered&quot;,&quot;complete&quot;:true}], expected code=200]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:6602,&quot;petId&quot;:66021,&quot;quantity&quot;:6,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;delivered&quot;,&quot;complete&quot;:true}], expected code=200]" methodname="test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:6602,&quot;petId&quot;:66021,&quot;quantity&quot;:6,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;delivered&quot;,&quot;complete&quot;:true}], expected code=200]" classname="TestStore" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:31.542593" end-time="2021-06-14 18:42:32.039806" duration="0.497213" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:33 Test case for finding an order, ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6602 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:36 Test Store Find Order By ID PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:33 Test case for finding an order, ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6602 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:36 Test Store Find Order By ID PASSED]]></output></test-case><test-case id="122" name="pythonapi/tests/test_store.py::TestStore::test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:777777,&quot;petId&quot;:66021,&quot;quantity&quot;:6,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;delivered&quot;,&quot;complete&quot;:true}], expected code=404]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:777777,&quot;petId&quot;:66021,&quot;quantity&quot;:6,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;delivered&quot;,&quot;complete&quot;:true}], expected code=404]" methodname="test_store_find_order_by_id[Find order [Data: {&quot;id&quot;:777777,&quot;petId&quot;:66021,&quot;quantity&quot;:6,&quot;shipDate&quot;:&quot;2021-02-03T19:43:55.849+00:00&quot;,&quot;status&quot;:&quot;delivered&quot;,&quot;complete&quot;:true}], expected code=404]" classname="TestStore" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:32.041769" end-time="2021-06-14 18:42:32.574314" duration="0.532545" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:33 Test case for finding an order, ID=777777
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/777777 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:36 Test Store Find Order By ID PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:33 Test case for finding an order, ID=777777
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/777777 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:36 Test Store Find Order By ID PASSED]]></output></test-case><test-case id="127" name="pythonapi/tests/test_store.py::TestStore::test_store_delete_order[Delete order [Data: 6600], expected code=200]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_delete_order[Delete order [Data: 6600], expected code=200]" methodname="test_store_delete_order[Delete order [Data: 6600], expected code=200]" classname="TestStore" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:34.653590" end-time="2021-06-14 18:42:35.150573" duration="0.496983" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_store.TestStore object at 0x7fc857a8ef10&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc857ab01f0&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_order_delete = (6600, 200)

    @mark.order(4)
    def test_store_delete_order(self, api, logger, dp_order_delete):
        logger.info(f"Test case for deleting an order, ID={dp_order_delete[0]}")
        response = api.store_delete_order(dp_order_delete[0])
&gt;       assert response.code == dp_order_delete[1]
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_store.py:42: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_store.py:42: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:40 Test case for deleting an order, ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/store/order/6600 HTTP/1.1" 404 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:40 Test case for deleting an order, ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/store/order/6600 HTTP/1.1" 404 None]]></output></test-case><test-case id="128" name="pythonapi/tests/test_store.py::TestStore::test_store_delete_order[Delete order [Data: 6601], expected code=200]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_delete_order[Delete order [Data: 6601], expected code=200]" methodname="test_store_delete_order[Delete order [Data: 6601], expected code=200]" classname="TestStore" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:35.152664" end-time="2021-06-14 18:42:36.178693" duration="1.026029" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:40 Test case for deleting an order, ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/store/order/6601 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:43 Order ID=6601 was deleted
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6601 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:47 Test Store Delete Order PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:40 Test case for deleting an order, ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/store/order/6601 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:43 Order ID=6601 was deleted
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/6601 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:47 Test Store Delete Order PASSED]]></output></test-case><test-case id="129" name="pythonapi/tests/test_store.py::TestStore::test_store_delete_order[Delete order [Data: 6602], expected code=200]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_delete_order[Delete order [Data: 6602], expected code=200]" methodname="test_store_delete_order[Delete order [Data: 6602], expected code=200]" classname="TestStore" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:36.180803" end-time="2021-06-14 18:42:36.691904" duration="0.511101" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_store.TestStore object at 0x7fc857a849d0&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc857ab01f0&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_order_delete = (6602, 200)

    @mark.order(4)
    def test_store_delete_order(self, api, logger, dp_order_delete):
        logger.info(f"Test case for deleting an order, ID={dp_order_delete[0]}")
        response = api.store_delete_order(dp_order_delete[0])
&gt;       assert response.code == dp_order_delete[1]
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_store.py:42: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_store.py:42: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:40 Test case for deleting an order, ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/store/order/6602 HTTP/1.1" 404 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:40 Test case for deleting an order, ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/store/order/6602 HTTP/1.1" 404 None]]></output></test-case><test-case id="130" name="pythonapi/tests/test_store.py::TestStore::test_store_delete_order[Delete order [Data: 777777], expected code=404]" fullname="pythonapi/tests/test_store.py::TestStore::test_store_delete_order[Delete order [Data: 777777], expected code=404]" methodname="test_store_delete_order[Delete order [Data: 777777], expected code=404]" classname="TestStore" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:36.693596" end-time="2021-06-14 18:42:37.691085" duration="0.997489" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_store.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:40 Test case for deleting an order, ID=777777
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/store/order/777777 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:43 Order ID=777777 was deleted
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/777777 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:47 Test Store Delete Order PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:40 Test case for deleting an order, ID=777777
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/store/order/777777 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:43 Order ID=777777 was deleted
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/store/order/777777 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_store.py:47 Test Store Delete Order PASSED]]></output></test-case><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /></test-suite><test-suite id="pythonapi/tests/test_user.py::TestUser" name="pythonapi/tests/test_user.py::TestUser" fullname="pythonapi/tests/test_user.py::TestUser" methodname="" classname="" runstate="Runnable" type="Assembly" testcasecount="20" result="Passed" label="" start-time="2021-06-14 18:42:20.563796" end-time="2021-06-14 18:42:48.922107" duration="28.358311" asserts="0" total="20" passed="10" failed="10" warnings="0" inconclusive="0" skipped="0"><properties><property name="python_version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /></properties><test-case id="104" name="pythonapi/tests/test_user.py::TestUser::test_user_create[Create user [Data: {&quot;id&quot;:6600,&quot;username&quot;:&quot;user6600&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6600&quot;,&quot;phone&quot;:&quot;6600&quot;,&quot;userStatus&quot;:1}], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_create[Create user [Data: {&quot;id&quot;:6600,&quot;username&quot;:&quot;user6600&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6600&quot;,&quot;phone&quot;:&quot;6600&quot;,&quot;userStatus&quot;:1}], expected code=200]" methodname="test_user_create[Create user [Data: {&quot;id&quot;:6600,&quot;username&quot;:&quot;user6600&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6600&quot;,&quot;phone&quot;:&quot;6600&quot;,&quot;userStatus&quot;:1}], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:20.563796" end-time="2021-06-14 18:42:21.511479" duration="0.947683" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:13 Test case for adding user with ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/user HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:17 User with ID=6600 was created.]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:13 Test case for adding user with ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/user HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:17 User with ID=6600 was created.]]></output></test-case><test-case id="105" name="pythonapi/tests/test_user.py::TestUser::test_user_create[Create user [Data: {&quot;id&quot;:6601,&quot;username&quot;:&quot;user6601&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6601&quot;,&quot;phone&quot;:&quot;6601&quot;,&quot;userStatus&quot;:2}], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_create[Create user [Data: {&quot;id&quot;:6601,&quot;username&quot;:&quot;user6601&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6601&quot;,&quot;phone&quot;:&quot;6601&quot;,&quot;userStatus&quot;:2}], expected code=200]" methodname="test_user_create[Create user [Data: {&quot;id&quot;:6601,&quot;username&quot;:&quot;user6601&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6601&quot;,&quot;phone&quot;:&quot;6601&quot;,&quot;userStatus&quot;:2}], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:21.513489" end-time="2021-06-14 18:42:22.033427" duration="0.519938" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:13 Test case for adding user with ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/user HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:17 User with ID=6601 was created.]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:13 Test case for adding user with ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/user HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:17 User with ID=6601 was created.]]></output></test-case><test-case id="106" name="pythonapi/tests/test_user.py::TestUser::test_user_create[Create user [Data: {&quot;id&quot;:6602,&quot;username&quot;:&quot;user6602&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6602&quot;,&quot;phone&quot;:&quot;6602&quot;,&quot;userStatus&quot;:3}], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_create[Create user [Data: {&quot;id&quot;:6602,&quot;username&quot;:&quot;user6602&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6602&quot;,&quot;phone&quot;:&quot;6602&quot;,&quot;userStatus&quot;:3}], expected code=200]" methodname="test_user_create[Create user [Data: {&quot;id&quot;:6602,&quot;username&quot;:&quot;user6602&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6602&quot;,&quot;phone&quot;:&quot;6602&quot;,&quot;userStatus&quot;:3}], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:22.036018" end-time="2021-06-14 18:42:22.540216" duration="0.504198" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:13 Test case for adding user with ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/user HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:17 User with ID=6602 was created.]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:13 Test case for adding user with ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/user HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:17 User with ID=6602 was created.]]></output></test-case><test-case id="113" name="pythonapi/tests/test_user.py::TestUser::test_user_login[Login with user name [user6600] and password [6600], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_login[Login with user name [user6600] and password [6600], expected code=200]" methodname="test_user_login[Login with user name [user6600] and password [6600], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:27.046460" end-time="2021-06-14 18:42:27.543108" duration="0.496648" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:21 Test case for logging with user name=user6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/login?username=user6600&amp;password=6600 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:25 User user6600 was logged.
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:26 Test User Login PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:21 Test case for logging with user name=user6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/login?username=user6600&amp;password=6600 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:25 User user6600 was logged.
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:26 Test User Login PASSED]]></output></test-case><test-case id="114" name="pythonapi/tests/test_user.py::TestUser::test_user_login[Login with user name [user6601] and password [6601], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_login[Login with user name [user6601] and password [6601], expected code=200]" methodname="test_user_login[Login with user name [user6601] and password [6601], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:27.544881" end-time="2021-06-14 18:42:28.069005" duration="0.524124" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:21 Test case for logging with user name=user6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/login?username=user6601&amp;password=6601 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:25 User user6601 was logged.
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:26 Test User Login PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:21 Test case for logging with user name=user6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/login?username=user6601&amp;password=6601 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:25 User user6601 was logged.
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:26 Test User Login PASSED]]></output></test-case><test-case id="115" name="pythonapi/tests/test_user.py::TestUser::test_user_login[Login with user name [user6602] and password [6602], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_login[Login with user name [user6602] and password [6602], expected code=200]" methodname="test_user_login[Login with user name [user6602] and password [6602], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:28.070358" end-time="2021-06-14 18:42:28.571219" duration="0.500861" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:21 Test case for logging with user name=user6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/login?username=user6602&amp;password=6602 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:25 User user6602 was logged.
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:26 Test User Login PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:21 Test case for logging with user name=user6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/login?username=user6602&amp;password=6602 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:25 User user6602 was logged.
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:26 Test User Login PASSED]]></output></test-case><test-case id="123" name="pythonapi/tests/test_user.py::TestUser::test_user_logout" fullname="pythonapi/tests/test_user.py::TestUser::test_user_logout" methodname="test_user_logout" classname="TestUser" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:32.578659" end-time="2021-06-14 18:42:33.089842" duration="0.511183" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_user.TestUser object at 0x7fc857a834f0&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc857a83d00&gt;, logger = &lt;RootLogger root (DEBUG)&gt;

    @mark.order(3)
    def test_user_logout(self, api, logger):
        logger.info("Test case for logging out from system")
        response = api.user_logout()
        assert response.code == 200
        assert response.type == ApiResponseType.ok
&gt;       assert response.message == "ok"
E       assert '{"code":200,...essage":"ok"}' == 'ok'
E         - ok
E         + {"code":200,"type":"unknown","message":"ok"}

pythonapi/tests/test_user.py:34: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_user.py:34: assert '{"code":200,...essage":"ok"}' == 'ok']]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:30 Test case for logging out from system
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/logout HTTP/1.1" 200 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:30 Test case for logging out from system
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/logout HTTP/1.1" 200 None]]></output></test-case><test-case id="131" name="pythonapi/tests/test_user.py::TestUser::test_user_find_by_name[Create user [Data: {&quot;id&quot;:6600,&quot;username&quot;:&quot;user6600&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6600&quot;,&quot;phone&quot;:&quot;6600&quot;,&quot;userStatus&quot;:1}], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_find_by_name[Create user [Data: {&quot;id&quot;:6600,&quot;username&quot;:&quot;user6600&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6600&quot;,&quot;phone&quot;:&quot;6600&quot;,&quot;userStatus&quot;:1}], expected code=200]" methodname="test_user_find_by_name[Create user [Data: {&quot;id&quot;:6600,&quot;username&quot;:&quot;user6600&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6600&quot;,&quot;phone&quot;:&quot;6600&quot;,&quot;userStatus&quot;:1}], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:37.693800" end-time="2021-06-14 18:42:38.195317" duration="0.501517" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_user.TestUser object at 0x7fc857ab0e50&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc857ab0340&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_user_find = ('{"id":6600,"username":"user6600","firstName":"Test","lastName":"Li","email":"TestLi@email.com","password":"6600","phone":"6600","userStatus":1}', 200)

    @mark.order(4)
    def test_user_find_by_name(self, api, logger, dp_user_find):
        _user = JsonTransmuter.transmute_from(dp_user_find[0], User)
        logger.info(f"Test case for finding user with name={_user.user_name}")
        response = api.user_find_by_name(_user.user_name)
&gt;       assert response.code == dp_user_find[1]
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_user.py:43: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_user.py:43: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:41 Test case for finding user with name=None
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/None HTTP/1.1" 404 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:41 Test case for finding user with name=None
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/None HTTP/1.1" 404 None]]></output></test-case><test-case id="132" name="pythonapi/tests/test_user.py::TestUser::test_user_find_by_name[Create user [Data: {&quot;id&quot;:6601,&quot;username&quot;:&quot;user6601&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6601&quot;,&quot;phone&quot;:&quot;6601&quot;,&quot;userStatus&quot;:2}], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_find_by_name[Create user [Data: {&quot;id&quot;:6601,&quot;username&quot;:&quot;user6601&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6601&quot;,&quot;phone&quot;:&quot;6601&quot;,&quot;userStatus&quot;:2}], expected code=200]" methodname="test_user_find_by_name[Create user [Data: {&quot;id&quot;:6601,&quot;username&quot;:&quot;user6601&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6601&quot;,&quot;phone&quot;:&quot;6601&quot;,&quot;userStatus&quot;:2}], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:38.197154" end-time="2021-06-14 18:42:38.695930" duration="0.498776" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_user.TestUser object at 0x7fc857aa11c0&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc857ab0340&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_user_find = ('{"id":6601,"username":"user6601","firstName":"Test","lastName":"Li","email":"TestLi@email.com","password":"6601","phone":"6601","userStatus":2}', 200)

    @mark.order(4)
    def test_user_find_by_name(self, api, logger, dp_user_find):
        _user = JsonTransmuter.transmute_from(dp_user_find[0], User)
        logger.info(f"Test case for finding user with name={_user.user_name}")
        response = api.user_find_by_name(_user.user_name)
&gt;       assert response.code == dp_user_find[1]
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_user.py:43: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_user.py:43: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:41 Test case for finding user with name=None
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/None HTTP/1.1" 404 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:41 Test case for finding user with name=None
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/None HTTP/1.1" 404 None]]></output></test-case><test-case id="133" name="pythonapi/tests/test_user.py::TestUser::test_user_find_by_name[Create user [Data: {&quot;id&quot;:6602,&quot;username&quot;:&quot;user6602&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6602&quot;,&quot;phone&quot;:&quot;6602&quot;,&quot;userStatus&quot;:3}], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_find_by_name[Create user [Data: {&quot;id&quot;:6602,&quot;username&quot;:&quot;user6602&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6602&quot;,&quot;phone&quot;:&quot;6602&quot;,&quot;userStatus&quot;:3}], expected code=200]" methodname="test_user_find_by_name[Create user [Data: {&quot;id&quot;:6602,&quot;username&quot;:&quot;user6602&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6602&quot;,&quot;phone&quot;:&quot;6602&quot;,&quot;userStatus&quot;:3}], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:38.699025" end-time="2021-06-14 18:42:39.195131" duration="0.496106" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_user.TestUser object at 0x7fc857ad96a0&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc857ab0340&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_user_find = ('{"id":6602,"username":"user6602","firstName":"Test","lastName":"Li","email":"TestLi@email.com","password":"6602","phone":"6602","userStatus":3}', 200)

    @mark.order(4)
    def test_user_find_by_name(self, api, logger, dp_user_find):
        _user = JsonTransmuter.transmute_from(dp_user_find[0], User)
        logger.info(f"Test case for finding user with name={_user.user_name}")
        response = api.user_find_by_name(_user.user_name)
&gt;       assert response.code == dp_user_find[1]
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_user.py:43: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_user.py:43: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:41 Test case for finding user with name=None
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/None HTTP/1.1" 404 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:41 Test case for finding user with name=None
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/None HTTP/1.1" 404 None]]></output></test-case><test-case id="134" name="pythonapi/tests/test_user.py::TestUser::test_user_find_by_name[Create user [Data: {&quot;id&quot;:10,&quot;username&quot;:&quot;theUser&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6600&quot;,&quot;phone&quot;:&quot;6600&quot;,&quot;userStatus&quot;:1}], expected code=404]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_find_by_name[Create user [Data: {&quot;id&quot;:10,&quot;username&quot;:&quot;theUser&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6600&quot;,&quot;phone&quot;:&quot;6600&quot;,&quot;userStatus&quot;:1}], expected code=404]" methodname="test_user_find_by_name[Create user [Data: {&quot;id&quot;:10,&quot;username&quot;:&quot;theUser&quot;,&quot;firstName&quot;:&quot;Test&quot;,&quot;lastName&quot;:&quot;Li&quot;,&quot;email&quot;:&quot;TestLi@email.com&quot;,&quot;password&quot;:&quot;6600&quot;,&quot;phone&quot;:&quot;6600&quot;,&quot;userStatus&quot;:1}], expected code=404]" classname="TestUser" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:39.196715" end-time="2021-06-14 18:42:39.703757" duration="0.507042" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:41 Test case for finding user with name=None
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/None HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:44 Test User Find by Name PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:41 Test case for finding user with name=None
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/None HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:44 Test User Find by Name PASSED]]></output></test-case><test-case id="138" name="pythonapi/tests/test_user.py::TestUser::test_user_update[Update user user6600], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_update[Update user user6600], expected code=200]" methodname="test_user_update[Update user user6600], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:41.255064" end-time="2021-06-14 18:42:42.263408" duration="1.008344" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_user.TestUser object at 0x7fc8579b9a90&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc8579b9820&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_user_update = ('user6600', '{"id":6600,"username":"user6600new","firstName":"Test","lastName":"Li","email":"TestLi@email.com","password":"6600","phone":"66000099","userStatus":1}', 200)

    @mark.order(5)
    def test_user_update(self, api, logger, dp_user_update):
        _user = JsonTransmuter.transmute_from(dp_user_update[1], User)
        logger.info(f"Test case for updating user with name={dp_user_update[0]}")
        response = api.user_update(dp_user_update[0], _user)
        assert response.code == dp_user_update[2]
        assert response.type == ApiResponseType.ok
        logger.info(f"User {dp_user_update[0]} was updated")
        response = api.user_find_by_name(_user)
&gt;       assert response.code == 200
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_user.py:55: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_user.py:55: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:49 Test case for updating user with name=user6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/user/user6600 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:53 User user6600 was updated
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/%3Cpythonapi.domain.user.User%20object%20at%200x7fc8579b9370%3E HTTP/1.1" 404 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:49 Test case for updating user with name=user6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/user/user6600 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:53 User user6600 was updated
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/%3Cpythonapi.domain.user.User%20object%20at%200x7fc8579b9370%3E HTTP/1.1" 404 None]]></output></test-case><test-case id="139" name="pythonapi/tests/test_user.py::TestUser::test_user_update[Update user user6601], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_update[Update user user6601], expected code=200]" methodname="test_user_update[Update user user6601], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:42.265105" end-time="2021-06-14 18:42:43.288185" duration="1.02308" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_user.TestUser object at 0x7fc85784c310&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc8579b9820&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_user_update = ('user6601', '{"id":6601,"username":"user6601new","firstName":"Test","lastName":"Li","email":"TestLi@email.com","password":"6601","phone":"66010099","userStatus":2}', 200)

    @mark.order(5)
    def test_user_update(self, api, logger, dp_user_update):
        _user = JsonTransmuter.transmute_from(dp_user_update[1], User)
        logger.info(f"Test case for updating user with name={dp_user_update[0]}")
        response = api.user_update(dp_user_update[0], _user)
        assert response.code == dp_user_update[2]
        assert response.type == ApiResponseType.ok
        logger.info(f"User {dp_user_update[0]} was updated")
        response = api.user_find_by_name(_user)
&gt;       assert response.code == 200
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_user.py:55: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_user.py:55: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:49 Test case for updating user with name=user6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/user/user6601 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:53 User user6601 was updated
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/%3Cpythonapi.domain.user.User%20object%20at%200x7fc85784c1c0%3E HTTP/1.1" 404 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:49 Test case for updating user with name=user6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/user/user6601 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:53 User user6601 was updated
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/%3Cpythonapi.domain.user.User%20object%20at%200x7fc85784c1c0%3E HTTP/1.1" 404 None]]></output></test-case><test-case id="140" name="pythonapi/tests/test_user.py::TestUser::test_user_update[Update user user6602], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_update[Update user user6602], expected code=200]" methodname="test_user_update[Update user user6602], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:43.290385" end-time="2021-06-14 18:42:44.307344" duration="1.016959" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_user.TestUser object at 0x7fc857853040&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc8579b9820&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_user_update = ('user6602', '{"id":6602,"username":"user6602new","firstName":"Test","lastName":"Li","email":"TestLi@email.com","password":"6602","phone":"66020099","userStatus":3}', 200)

    @mark.order(5)
    def test_user_update(self, api, logger, dp_user_update):
        _user = JsonTransmuter.transmute_from(dp_user_update[1], User)
        logger.info(f"Test case for updating user with name={dp_user_update[0]}")
        response = api.user_update(dp_user_update[0], _user)
        assert response.code == dp_user_update[2]
        assert response.type == ApiResponseType.ok
        logger.info(f"User {dp_user_update[0]} was updated")
        response = api.user_find_by_name(_user)
&gt;       assert response.code == 200
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_user.py:55: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_user.py:55: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:49 Test case for updating user with name=user6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/user/user6602 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:53 User user6602 was updated
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/%3Cpythonapi.domain.user.User%20object%20at%200x7fc857853e80%3E HTTP/1.1" 404 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:49 Test case for updating user with name=user6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/user/user6602 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:53 User user6602 was updated
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/%3Cpythonapi.domain.user.User%20object%20at%200x7fc857853e80%3E HTTP/1.1" 404 None]]></output></test-case><test-case id="141" name="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6600], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6600], expected code=200]" methodname="test_user_delete[Delete user user6600], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:44.309193" end-time="2021-06-14 18:42:44.855666" duration="0.546473" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_user.TestUser object at 0x7fc857ab0940&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc8579b9820&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_user_delete = ('user6600', 200)

    @mark.order(6)
    def test_user_delete(self, api, logger, dp_user_delete):
        logger.info(f"Test case for deleting user {dp_user_delete[0]}")
        response = api.user_delete(dp_user_delete[0])
&gt;       assert response.code == dp_user_delete[1]
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_user.py:62: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_user.py:62: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6600 HTTP/1.1" 404 0]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6600 HTTP/1.1" 404 0]]></output></test-case><test-case id="142" name="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6600], expected code=404]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6600], expected code=404]" methodname="test_user_delete[Delete user user6600], expected code=404]" classname="TestUser" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:44.857786" end-time="2021-06-14 18:42:45.889591" duration="1.031805" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6600 HTTP/1.1" 404 0
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:63 User user6600 was deleted
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/user6600 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:67 Test User Delete PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6600 HTTP/1.1" 404 0
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:63 User user6600 was deleted
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/user6600 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:67 Test User Delete PASSED]]></output></test-case><test-case id="143" name="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6601], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6601], expected code=200]" methodname="test_user_delete[Delete user user6601], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:45.891259" end-time="2021-06-14 18:42:46.372567" duration="0.481308" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_user.TestUser object at 0x7fc85787b2b0&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc8579b9820&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_user_delete = ('user6601', 200)

    @mark.order(6)
    def test_user_delete(self, api, logger, dp_user_delete):
        logger.info(f"Test case for deleting user {dp_user_delete[0]}")
        response = api.user_delete(dp_user_delete[0])
&gt;       assert response.code == dp_user_delete[1]
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_user.py:62: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_user.py:62: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6601 HTTP/1.1" 404 0]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6601 HTTP/1.1" 404 0]]></output></test-case><test-case id="144" name="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6601], expected code=404]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6601], expected code=404]" methodname="test_user_delete[Delete user user6601], expected code=404]" classname="TestUser" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:46.374499" end-time="2021-06-14 18:42:47.370270" duration="0.995771" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6601 HTTP/1.1" 404 0
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:63 User user6601 was deleted
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/user6601 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:67 Test User Delete PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6601 HTTP/1.1" 404 0
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:63 User user6601 was deleted
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/user6601 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:67 Test User Delete PASSED]]></output></test-case><test-case id="145" name="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6602], expected code=200]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6602], expected code=200]" methodname="test_user_delete[Delete user user6602], expected code=200]" classname="TestUser" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:47.373102" end-time="2021-06-14 18:42:47.893099" duration="0.519997" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_user.TestUser object at 0x7fc857a8ed60&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc8579b9820&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_user_delete = ('user6602', 200)

    @mark.order(6)
    def test_user_delete(self, api, logger, dp_user_delete):
        logger.info(f"Test case for deleting user {dp_user_delete[0]}")
        response = api.user_delete(dp_user_delete[0])
&gt;       assert response.code == dp_user_delete[1]
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_user.py:62: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_user.py:62: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6602 HTTP/1.1" 404 0]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6602 HTTP/1.1" 404 0]]></output></test-case><test-case id="146" name="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6602], expected code=404]" fullname="pythonapi/tests/test_user.py::TestUser::test_user_delete[Delete user user6602], expected code=404]" methodname="test_user_delete[Delete user user6602], expected code=404]" classname="TestUser" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:47.894672" end-time="2021-06-14 18:42:48.922107" duration="1.027435" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_user.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6602 HTTP/1.1" 404 0
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:63 User user6602 was deleted
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/user6602 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:67 Test User Delete PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:60 Test case for deleting user user6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/user/user6602 HTTP/1.1" 404 0
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:63 User user6602 was deleted
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/user/user6602 HTTP/1.1" 404 None
&#x1b;[32mINFO    &#x1b;[0m root:test_user.py:67 Test User Delete PASSED]]></output></test-case><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /></test-suite><test-suite id="pythonapi/tests/test_pet.py::TestPet" name="pythonapi/tests/test_pet.py::TestPet" fullname="pythonapi/tests/test_pet.py::TestPet" methodname="" classname="" runstate="Runnable" type="Assembly" testcasecount="15" result="Passed" label="" start-time="2021-06-14 18:42:17.191918" end-time="2021-06-14 18:42:41.251767" duration="24.059849" asserts="0" total="15" passed="12" failed="3" warnings="0" inconclusive="0" skipped="0"><properties><property name="python_version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /></properties><test-case id="100" name="pythonapi/tests/test_pet.py::TestPet::test_pet_add[Data=[{&quot;id&quot;:6600,&quot;name&quot;:&quot;dog6600&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;available&quot;}], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_add[Data=[{&quot;id&quot;:6600,&quot;name&quot;:&quot;dog6600&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;available&quot;}], expected code=200]" methodname="test_pet_add[Data=[{&quot;id&quot;:6600,&quot;name&quot;:&quot;dog6600&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;available&quot;}], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:17.191918" end-time="2021-06-14 18:42:17.722087" duration="0.530169" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:16 Test case for adding pet with ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:21 Pet with ID=6600 was added.]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:16 Test case for adding pet with ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:21 Pet with ID=6600 was added.]]></output></test-case><test-case id="101" name="pythonapi/tests/test_pet.py::TestPet::test_pet_add[Data=[{&quot;id&quot;:6601,&quot;name&quot;:&quot;dog6601&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;pending&quot;}], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_add[Data=[{&quot;id&quot;:6601,&quot;name&quot;:&quot;dog6601&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;pending&quot;}], expected code=200]" methodname="test_pet_add[Data=[{&quot;id&quot;:6601,&quot;name&quot;:&quot;dog6601&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;pending&quot;}], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:17.723879" end-time="2021-06-14 18:42:18.244840" duration="0.520961" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:16 Test case for adding pet with ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:21 Pet with ID=6601 was added.]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:16 Test case for adding pet with ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:21 Pet with ID=6601 was added.]]></output></test-case><test-case id="102" name="pythonapi/tests/test_pet.py::TestPet::test_pet_add[Data=[{&quot;id&quot;:6602,&quot;name&quot;:&quot;dog6602&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;sold&quot;}], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_add[Data=[{&quot;id&quot;:6602,&quot;name&quot;:&quot;dog6602&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;sold&quot;}], expected code=200]" methodname="test_pet_add[Data=[{&quot;id&quot;:6602,&quot;name&quot;:&quot;dog6602&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;sold&quot;}], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:18.246674" end-time="2021-06-14 18:42:19.184734" duration="0.93806" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:16 Test case for adding pet with ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:21 Pet with ID=6602 was added.]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:16 Test case for adding pet with ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "POST /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:21 Pet with ID=6602 was added.]]></output></test-case><test-case id="107" name="pythonapi/tests/test_pet.py::TestPet::test_pet_update[Data=[{&quot;id&quot;:6600,&quot;name&quot;:&quot;new-dog6600&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;sold&quot;}], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_update[Data=[{&quot;id&quot;:6600,&quot;name&quot;:&quot;new-dog6600&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;sold&quot;}], expected code=200]" methodname="test_pet_update[Data=[{&quot;id&quot;:6600,&quot;name&quot;:&quot;new-dog6600&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;sold&quot;}], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:22.543630" end-time="2021-06-14 18:42:23.060268" duration="0.516638" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:27 Test case for updating pet to the store
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:32 Pet with ID=6600 was updated.]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:27 Test case for updating pet to the store
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:32 Pet with ID=6600 was updated.]]></output></test-case><test-case id="108" name="pythonapi/tests/test_pet.py::TestPet::test_pet_update[Data=[{&quot;id&quot;:6601,&quot;name&quot;:&quot;new-dog6601&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;available&quot;}], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_update[Data=[{&quot;id&quot;:6601,&quot;name&quot;:&quot;new-dog6601&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;available&quot;}], expected code=200]" methodname="test_pet_update[Data=[{&quot;id&quot;:6601,&quot;name&quot;:&quot;new-dog6601&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;available&quot;}], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:23.061789" end-time="2021-06-14 18:42:23.544073" duration="0.482284" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:27 Test case for updating pet to the store
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:32 Pet with ID=6601 was updated.]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:27 Test case for updating pet to the store
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:32 Pet with ID=6601 was updated.]]></output></test-case><test-case id="109" name="pythonapi/tests/test_pet.py::TestPet::test_pet_update[Data=[{&quot;id&quot;:6602,&quot;name&quot;:&quot;new-dog6602&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;pending&quot;}], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_update[Data=[{&quot;id&quot;:6602,&quot;name&quot;:&quot;new-dog6602&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;pending&quot;}], expected code=200]" methodname="test_pet_update[Data=[{&quot;id&quot;:6602,&quot;name&quot;:&quot;new-dog6602&quot;,&quot;category&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Dogs&quot;},&quot;photoUrls&quot;:[&quot;string&quot;],&quot;tags&quot;:[{&quot;id&quot;:0,&quot;name&quot;:&quot;string&quot;}],&quot;status&quot;:&quot;pending&quot;}], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:23.545900" end-time="2021-06-14 18:42:24.060567" duration="0.514667" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:27 Test case for updating pet to the store
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:32 Pet with ID=6602 was updated.]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:27 Test case for updating pet to the store
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "PUT /v2/pet HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:32 Pet with ID=6602 was updated.]]></output></test-case><test-case id="116" name="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_status[Pet status=[available], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_status[Pet status=[available], expected code=200]" methodname="test_pet_find_by_status[Pet status=[available], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:28.575409" end-time="2021-06-14 18:42:29.330441" duration="0.755032" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:37 Test case for finding pet by status [available]
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByStatus?status=available HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:42 Test Find Pet by Status PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:37 Test case for finding pet by status [available]
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByStatus?status=available HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:42 Test Find Pet by Status PASSED]]></output></test-case><test-case id="117" name="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_status[Pet status=[pending], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_status[Pet status=[pending], expected code=200]" methodname="test_pet_find_by_status[Pet status=[pending], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:29.332768" end-time="2021-06-14 18:42:29.976077" duration="0.643309" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:37 Test case for finding pet by status [pending]
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByStatus?status=pending HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:42 Test Find Pet by Status PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:37 Test case for finding pet by status [pending]
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByStatus?status=pending HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:42 Test Find Pet by Status PASSED]]></output></test-case><test-case id="118" name="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_status[Pet status=[sold], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_status[Pet status=[sold], expected code=200]" methodname="test_pet_find_by_status[Pet status=[sold], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:29.978360" end-time="2021-06-14 18:42:30.494129" duration="0.515769" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:37 Test case for finding pet by status [sold]
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByStatus?status=sold HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:42 Test Find Pet by Status PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:37 Test case for finding pet by status [sold]
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByStatus?status=sold HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:42 Test Find Pet by Status PASSED]]></output></test-case><test-case id="124" name="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_tags[Pet tags=[['{&quot;id&quot;:0,&quot;name&quot;:&quot;Tag1&quot;}']], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_tags[Pet tags=[['{&quot;id&quot;:0,&quot;name&quot;:&quot;Tag1&quot;}']], expected code=200]" methodname="test_pet_find_by_tags[Pet tags=[['{&quot;id&quot;:0,&quot;name&quot;:&quot;Tag1&quot;}']], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:33.093371" end-time="2021-06-14 18:42:33.624904" duration="0.531533" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:47 Test case for finding pet by tags list
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByTags?tags=Tag1 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:52 Test Find Pet by Tag PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:47 Test case for finding pet by tags list
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByTags?tags=Tag1 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:52 Test Find Pet by Tag PASSED]]></output></test-case><test-case id="125" name="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_tags[Pet tags=[['{&quot;id&quot;:0,&quot;name&quot;:&quot;Tag1&quot;}', '{&quot;id&quot;:22,&quot;name&quot;:&quot;tag2&quot;}']], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_tags[Pet tags=[['{&quot;id&quot;:0,&quot;name&quot;:&quot;Tag1&quot;}', '{&quot;id&quot;:22,&quot;name&quot;:&quot;tag2&quot;}']], expected code=200]" methodname="test_pet_find_by_tags[Pet tags=[['{&quot;id&quot;:0,&quot;name&quot;:&quot;Tag1&quot;}', '{&quot;id&quot;:22,&quot;name&quot;:&quot;tag2&quot;}']], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:33.626373" end-time="2021-06-14 18:42:34.126890" duration="0.500517" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:47 Test case for finding pet by tags list
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByTags?tags=Tag1&amp;tags=tag2 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:52 Test Find Pet by Tag PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:47 Test case for finding pet by tags list
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByTags?tags=Tag1&amp;tags=tag2 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:52 Test Find Pet by Tag PASSED]]></output></test-case><test-case id="126" name="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_tags[Pet tags=[['{&quot;id&quot;:10,&quot;name&quot;:&quot;tag11&quot;}']], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_find_by_tags[Pet tags=[['{&quot;id&quot;:10,&quot;name&quot;:&quot;tag11&quot;}']], expected code=200]" methodname="test_pet_find_by_tags[Pet tags=[['{&quot;id&quot;:10,&quot;name&quot;:&quot;tag11&quot;}']], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Passed" label="" start-time="2021-06-14 18:42:34.129258" end-time="2021-06-14 18:42:34.649405" duration="0.520147" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[]]></message><stack-trace><![CDATA[None]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:47 Test case for finding pet by tags list
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByTags?tags=tag11 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:52 Test Find Pet by Tag PASSED]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:47 Test case for finding pet by tags list
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "GET /v2/pet/findByTags?tags=tag11 HTTP/1.1" 200 None
&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:52 Test Find Pet by Tag PASSED]]></output></test-case><test-case id="135" name="pythonapi/tests/test_pet.py::TestPet::test_pet_delete[Pet ID=[6600], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_delete[Pet ID=[6600], expected code=200]" methodname="test_pet_delete[Pet ID=[6600], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:39.707499" end-time="2021-06-14 18:42:40.234640" duration="0.527141" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_pet.TestPet object at 0x7fc85785c430&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc85785ca30&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_pet_delete = (6600, 'API_KEY', 200)

    @allure.testcase("Test Pet Delete")
    @mark.order(5)
    def test_pet_delete(self, api, logger, dp_pet_delete):
        logger.info(f"Test case for deleting pet ID={dp_pet_delete[0]}")
        response = api.pet_delete(dp_pet_delete[0], dp_pet_delete[1])
&gt;       assert response.code == dp_pet_delete[2]
E       assert 404 == 200
E         +404
E         -200

pythonapi/tests/test_pet.py:59: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_pet.py:59: assert 404 == 200]]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:57 Test case for deleting pet ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/pet/6600 HTTP/1.1" 404 0]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:57 Test case for deleting pet ID=6600
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/pet/6600 HTTP/1.1" 404 0]]></output></test-case><test-case id="136" name="pythonapi/tests/test_pet.py::TestPet::test_pet_delete[Pet ID=[6601], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_delete[Pet ID=[6601], expected code=200]" methodname="test_pet_delete[Pet ID=[6601], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:40.236448" end-time="2021-06-14 18:42:40.747892" duration="0.511444" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_pet.TestPet object at 0x7fc857853b20&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc85785ca30&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_pet_delete = (6601, 'API_KEY', 200)

    @allure.testcase("Test Pet Delete")
    @mark.order(5)
    def test_pet_delete(self, api, logger, dp_pet_delete):
        logger.info(f"Test case for deleting pet ID={dp_pet_delete[0]}")
        response = api.pet_delete(dp_pet_delete[0], dp_pet_delete[1])
        assert response.code == dp_pet_delete[2]
        assert response.type == ApiResponseType.ok
&gt;       assert response.message == "Pet deleted"
E       assert '{"code":200,...sage":"6601"}' == 'Pet deleted'
E         - Pet deleted
E         + {"code":200,"type":"unknown","message":"6601"}

pythonapi/tests/test_pet.py:61: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_pet.py:61: assert '{"code":200,...sage":"6601"}' == 'Pet deleted']]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:57 Test case for deleting pet ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/pet/6601 HTTP/1.1" 200 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:57 Test case for deleting pet ID=6601
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/pet/6601 HTTP/1.1" 200 None]]></output></test-case><test-case id="137" name="pythonapi/tests/test_pet.py::TestPet::test_pet_delete[Pet ID=[6602], expected code=200]" fullname="pythonapi/tests/test_pet.py::TestPet::test_pet_delete[Pet ID=[6602], expected code=200]" methodname="test_pet_delete[Pet ID=[6602], expected code=200]" classname="TestPet" runstate="Runnable" seed="1" result="Failed" label="" start-time="2021-06-14 18:42:40.750231" end-time="2021-06-14 18:42:41.251767" duration="0.501536" asserts="0"><properties><property name="python-version" value="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" /><property name="fspath" value="pythonapi/tests/test_pet.py" /></properties><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /><failure><message><![CDATA[self = &lt;pythonapi.tests.test_pet.TestPet object at 0x7fc85785c820&gt;, api = &lt;pythonapi.core.api_test.ApiTest object at 0x7fc85785ca30&gt;, logger = &lt;RootLogger root (DEBUG)&gt;
dp_pet_delete = (6602, 'API_KEY', 200)

    @allure.testcase("Test Pet Delete")
    @mark.order(5)
    def test_pet_delete(self, api, logger, dp_pet_delete):
        logger.info(f"Test case for deleting pet ID={dp_pet_delete[0]}")
        response = api.pet_delete(dp_pet_delete[0], dp_pet_delete[1])
        assert response.code == dp_pet_delete[2]
        assert response.type == ApiResponseType.ok
&gt;       assert response.message == "Pet deleted"
E       assert '{"code":200,...sage":"6602"}' == 'Pet deleted'
E         - Pet deleted
E         + {"code":200,"type":"unknown","message":"6602"}

pythonapi/tests/test_pet.py:61: AssertionError]]></message><stack-trace><![CDATA[/workspace/pythonapi/tests/test_pet.py:61: assert '{"code":200,...sage":"6602"}' == 'Pet deleted']]></stack-trace></failure><reason><message><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:57 Test case for deleting pet ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/pet/6602 HTTP/1.1" 200 None]]></message></reason><output><![CDATA[&#x1b;[32mINFO    &#x1b;[0m root:test_pet.py:57 Test case for deleting pet ID=6602
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): petstore.swagger.io:443
&#x1b;[35mDEBUG   &#x1b;[0m urllib3.connectionpool:connectionpool.py:452 https://petstore.swagger.io:443 "DELETE /v2/pet/6602 HTTP/1.1" 200 None]]></output></test-case><environment framework-version="3.6.2" clr-version="3.9.5 (default, May 11 2021, 08:20:37) &#10;[GCC 10.3.0]" os-version="5.10.25-linuxkit" platform="Linux" cwd="/workspace" machine-name="x86_64" user="" user-domain="" culture="en_US" uiculture="en_US" os-architecture="64bit" /></test-suite></test-run>